workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "integration"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

stages:
  - test
  - package

variables:
  PM4PY_DEFAULT_ENABLE_VISUALIZATIONS_VIEW: "False"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

default:
  image: python:3.12
  cache:
    key: pip-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
  before_script:
    - mkdir -p "$PIP_CACHE_DIR"
    - apt-get update -y
    - apt-get install -y graphviz
    - python -m pip install --upgrade pip
    - python -m pip install --group ci
    - python -m pip install .

test_scripts:
  stage: test
  script:
    - cd tests
    - python execute_tests.py --pipeline
  # If execute_tests.py returns non-zero, job fails.
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "integration"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
      # This job is run in merge requests

example_scripts:
  stage: test
  script:
    - cd examples
    - python execute_everything.py --pipeline
  # If execute_everything.py returns non-zero, job fails.
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "integration"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
      # This job is run in merge requests

linting_scripts:
  stage: test
  script:
    - python -m pip install --group lint
    - cd files
    - python flake8_score.py
  # If flake8_score.py returns non-zero, job fails.
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "integration"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
      # do not run this job in merge requests

package_build:
  stage: package
  script:
    - python -m pip install --group build
    - python -m build
    - python -m twine check dist/*
  rules:
    - if: $CI_COMMIT_BRANCH == "staging"
      when: always
    - if: $CI_COMMIT_BRANCH == "integration"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never
