from pm4py.algo.simulation.playout.ocpn.variants import extensive
from pm4py.util import exec_utils
from enum import Enum
from pm4py.objects.ocpn.obj import OCPetriNet, OCMarking
from typing import Optional, Dict, Any
from pm4py.objects.ocel.obj import OCEL  


class Variants(Enum):
    EXTENSIVE = extensive


DEFAULT_VARIANT = Variants.EXTENSIVE
VERSIONS = {Variants.EXTENSIVE}


def apply(ocpn: OCPetriNet, initial_marking: OCMarking, final_marking: OCMarking, parameters: Optional[Dict[Any, Any]] = None, variant=DEFAULT_VARIANT) -> OCEL:
    """
    Do the playout of an object-centric Petri net generating an OCEL 2.0.

    Parameters
    -----------
    ocpn
        Object-centric Petri net to play-out
    initial_marking
        Initial marking of the object-centric Petri net
    final_marking
        Final marking of the object-centric Petri net
    parameters
        Parameters of the algorithm
    variant
        Variant of the algorithm to use:
            - Variants.EXTENSIVE: gets all the traces from the model. Can be expensive

    Returns
    -----------
    OCEL
        Object-centric event log generated by the playout of the object-centric Petri net
    """
    return exec_utils.get_variant(variant).apply(ocpn, initial_marking, final_marking=final_marking,
                                                 parameters=parameters)
