from pm4py.algo.simulation.playout.oc_causal_net.variants import extensive
from pm4py.util import exec_utils
from enum import Enum
from pm4py.objects.oc_causal_net.obj import OCCausalNet
from typing import Optional, Dict, Any
from pm4py.objects.ocel.obj import OCEL  


class Variants(Enum):
    EXTENSIVE = extensive


DEFAULT_VARIANT = Variants.EXTENSIVE
VERSIONS = {Variants.EXTENSIVE}


def apply(occn: OCCausalNet, objects, parameters: Optional[Dict[Any, Any]] = None, variant=DEFAULT_VARIANT) -> OCEL:
    """
    Do the playout of an object-centric causal net generating an OCEL.

    Parameters
    -----------
    occn
        Object-centric causal net to play-out
    objects
        Dictionary mapping object types to object ids. These objects will be introduced by the start activities of the occn at the beginning of every binding sequence.
    parameters
        Parameters of the algorithm
    variant
        Variant of the algorithm to use:
            - Variants.EXTENSIVE: gets all the traces from the model. can be expensive
            
    Returns
    -----------
    OCEL
        Object-centric event log generated by the playout of the object-centric causal net
    """
    return exec_utils.get_variant(variant).apply(occn, objects, parameters=parameters)
